version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./app.py:/app/app.py  # Agregamos el montaje de app.py en /app/app.py
